import { ConfigService } from '@nestjs/config';
import { ReminderSchedulerService } from './reminder-scheduler.service';
import { PrismaService } from '../prisma/prisma.service';

function makePrismaMock(overrides: { leads: unknown[]; existingTask?: unknown | null }) {
  return {
    lead: { findMany: jest.fn().mockResolvedValue(overrides.leads) },
    task: {
      findFirst: jest.fn().mockResolvedValue(overrides.existingTask ?? null),
      create: jest.fn().mockResolvedValue({}),
    },
  } as unknown as PrismaService;
}

describe('ReminderSchedulerService.generateDueReminders', () => {
  const config = new ConfigService({ TIMEZONE: 'UTC' });
  const now = new Date('2026-06-15T12:00:00.000Z');

  it('creates a reminder task for a lead whose planned purchase date is ~1 day away', async () => {
    const plannedDate = new Date('2026-06-16T12:00:00.000Z'); // exactly +24h
    const prisma = makePrismaMock({
      leads: [
        {
          id: 'lead-1',
          managerId: 'manager-1',
          plannedPurchaseDate: plannedDate,
          firstName: 'A',
          lastName: 'B',
        },
      ],
      existingTask: null,
    });
    const service = new ReminderSchedulerService(prisma, config);

    const created = await service.generateDueReminders(now);

    expect(created).toBe(1);
    expect(prisma.task.create as jest.Mock).toHaveBeenCalledWith(
      expect.objectContaining({
        data: expect.objectContaining({
          leadId: 'lead-1',
          assignedToUserId: 'manager-1',
          isAutoGenerated: true,
          sourcePlannedPurchaseDate: plannedDate,
        }),
      }),
    );
  });

  it('does not duplicate a reminder that was already generated for the same planned date', async () => {
    const plannedDate = new Date('2026-06-16T12:00:00.000Z');
    const prisma = makePrismaMock({
      leads: [{ id: 'lead-1', managerId: 'manager-1', plannedPurchaseDate: plannedDate }],
      existingTask: { id: 'existing-task' },
    });
    const service = new ReminderSchedulerService(prisma, config);

    const created = await service.generateDueReminders(now);

    expect(created).toBe(0);
    expect(prisma.task.create).not.toHaveBeenCalled();
  });

  it('skips leads with no assigned manager', async () => {
    const plannedDate = new Date('2026-06-16T12:00:00.000Z');
    const prisma = makePrismaMock({
      leads: [{ id: 'lead-1', managerId: null, plannedPurchaseDate: plannedDate }],
    });
    const service = new ReminderSchedulerService(prisma, config);

    const created = await service.generateDueReminders(now);

    expect(created).toBe(0);
    expect(prisma.task.create).not.toHaveBeenCalled();
  });
});
