import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { Cron, CronExpression } from '@nestjs/schedule';
import { DateTime } from 'luxon';
import { PrismaService } from '../prisma/prisma.service';

const WINDOW_START_HOURS = 23;
const WINDOW_END_HOURS = 25;
const BUSINESS_HOUR_LOCAL = 10;

@Injectable()
export class ReminderSchedulerService {
  private readonly logger = new Logger(ReminderSchedulerService.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly config: ConfigService,
  ) {}

  private computeDueAt(now: Date): Date {
    const zone = this.config.get<string>('TIMEZONE', 'UTC');
    const nowLocal = DateTime.fromJSDate(now, { zone });
    const businessSlotToday = nowLocal.set({
      hour: BUSINESS_HOUR_LOCAL,
      minute: 0,
      second: 0,
      millisecond: 0,
    });
    return (nowLocal < businessSlotToday ? businessSlotToday : nowLocal).toJSDate();
  }

  @Cron(CronExpression.EVERY_HOUR)
  async handleCron() {
    // Cron ticks run outside the HTTP request cycle, so Nest's exception filters
    // never see a rejection here — an uncaught one (e.g. a transient DB outage
    // during this tick) would otherwise crash the whole process, not just skip
    // this run. Log and let the next scheduled tick retry instead.
    try {
      await this.generateDueReminders(new Date());
    } catch (err) {
      this.logger.error('Reminder generation failed — will retry next tick', err as Error);
    }
  }

  /** Exposed separately from the @Cron entrypoint so tests can call it directly
   * with a fixed `now` instead of waiting on real timers. */
  async generateDueReminders(now: Date): Promise<number> {
    const windowStart = new Date(now.getTime() + WINDOW_START_HOURS * 60 * 60 * 1000);
    const windowEnd = new Date(now.getTime() + WINDOW_END_HOURS * 60 * 60 * 1000);

    const dueLeads = await this.prisma.lead.findMany({
      where: {
        deletedAt: null,
        managerId: { not: null },
        plannedPurchaseDate: { gte: windowStart, lte: windowEnd },
      },
      select: {
        id: true,
        managerId: true,
        plannedPurchaseDate: true,
        firstName: true,
        lastName: true,
      },
    });

    let created = 0;
    for (const lead of dueLeads) {
      if (!lead.managerId || !lead.plannedPurchaseDate) continue;

      const existing = await this.prisma.task.findFirst({
        where: {
          leadId: lead.id,
          isAutoGenerated: true,
          sourcePlannedPurchaseDate: lead.plannedPurchaseDate,
          status: 'PENDING',
        },
      });
      if (existing) continue;

      await this.prisma.task.create({
        data: {
          leadId: lead.id,
          assignedToUserId: lead.managerId,
          dueAt: this.computeDueAt(now),
          contactType: 'OTHER',
          comment: `Клиент ${lead.firstName} ${lead.lastName} планирует покупку автомобиля завтра — уточните статус.`,
          isAutoGenerated: true,
          sourcePlannedPurchaseDate: lead.plannedPurchaseDate,
        },
      });
      created += 1;
    }

    if (created > 0) {
      this.logger.log(`Generated ${created} planned-purchase reminder task(s).`);
    }
    return created;
  }
}
