import type {
  ContactType,
  InteractionType,
  MessengerType,
  Role,
  TaskStatus,
  Temperature,
  VehicleInterestType,
} from '@crm/shared';

export interface SafeUser {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
  role: Role;
  isActive?: boolean;
  createdAt?: string;
}

export interface LeadSource {
  id: string;
  name: string;
  order: number;
  isActive: boolean;
}

export interface LossReason {
  id: string;
  name: string;
  order: number;
  isActive: boolean;
}

export interface Tariff {
  id: string;
  name: string;
  description: string | null;
  price: string;
  isActive: boolean;
}

export interface LeadStatus {
  id: string;
  key: string;
  name: string;
  order: number;
  color: string | null;
  isWon: boolean;
  isLost: boolean;
  isDefault: boolean;
  isActive: boolean;
}

export interface VehicleInterest {
  id: string;
  interestType: VehicleInterestType;
  make: string | null;
  model: string | null;
  year: number | null;
  budget: string | null;
  comment: string | null;
}

export interface Lead {
  id: string;
  firstName: string;
  lastName: string;
  phone: string;
  messengerType: MessengerType | null;
  messengerContact: string | null;
  additionalContactInfo: string | null;
  firstContactDate: string;
  source: LeadSource;
  manager: { id: string; firstName: string; lastName: string; email: string } | null;
  status: LeadStatus;
  temperature: Temperature;
  contactReason: string | null;
  managerNotes: string | null;
  interestedTariff: Tariff | null;
  purchasedTariff: Tariff | null;
  plannedPurchasePeriodText: string | null;
  plannedPurchaseDate: string | null;
  plannedPurchaseComment: string | null;
  purchasedCarMake: string | null;
  purchasedCarModel: string | null;
  purchasedCarYear: number | null;
  purchasePrice: string | null;
  purchaseDate: string | null;
  lossReason: LossReason | null;
  lossComment: string | null;
  vehicleInterest: VehicleInterest | null;
  version: number;
  createdAt: string;
  updatedAt: string;
}

export interface Task {
  id: string;
  leadId: string;
  lead: { id: string; firstName: string; lastName: string; phone: string };
  assignedTo: { id: string; firstName: string; lastName: string };
  dueAt: string;
  contactType: ContactType;
  comment: string | null;
  status: TaskStatus;
  isAutoGenerated: boolean;
  version: number;
}

export interface Interaction {
  id: string;
  type: InteractionType;
  comment: string;
  occurredAt: string;
  author: { id: string; firstName: string; lastName: string };
}

export interface TimelineEntry {
  kind: 'INTERACTION' | 'AUDIT';
  at: string;
  id: string;
  type?: InteractionType;
  comment?: string;
  action?: string;
  entityType?: string;
  changes?: Record<string, { old: unknown; new: unknown }>;
  author: { id: string; firstName: string; lastName: string } | null;
}

export interface ManagerDashboard {
  leads: {
    total: number;
    newCount: number;
    activeCount: number;
    boughtCount: number;
    notBoughtCount: number;
    planningPurchaseCount: number;
  };
  tasks: {
    todayTasks: Task[];
    overdueTasks: Task[];
    todayCount: number;
    overdueCount: number;
  };
}

export interface AdminDashboard extends ManagerDashboard {
  conversionRate: number;
  perManager: { managerId: string | null; manager: SafeUser | null; leadCount: number }[];
  bySource: { sourceId: string; name: string; count: number }[];
  byLossReason: { lossReasonId: string | null; name: string; count: number }[];
}

export interface Paginated<T> {
  items: T[];
  total: number;
}
